# Dockerfile
FROM openjdk:11
ARG JAR_FILE=demo-1.0.jar
COPY ${JAR_FILE} demo01.jar
EXPOSE 9040
ENTRYPOINT ["java", "-jar", "/demo01.jar"]

#FROM openjdk:11
#ENV APP_HOME=/usr/app/
#WORKDIR $APP_HOME
#COPY build/libs/*.jar demo-1.0.jar
#EXPOSE 8014
#CMD ["java", "-jar", "demo-1.0.jar"]

